CLIENT_SECRET=A4xZMgUj7mNzC4191oHDmx6W89Mvsgav
export REALM_FILE_TO_IMPORT=./demo-realm.json

export OAUTH2_PROXY_CLIENT_SECRET=${CLIENT_SECRET}

export OIDC_CLIENT_SECRET=${CLIENT_SECRET}
export OIDC_CRYPTO_PASSPHRASE=foo
